config/routes.rb
Rails.application.routes.draw do
  
  resources :blogs do
    resources :entries, except: [:index]
  end

  resources :entries, only: [] do
    resources :comments, only: [:create, :destroy]
    patch '/comments/:id/approve' => 'comments#approve', as: 'comment_approve'
  end

  root to: 'blogs#index'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :entries
  has_many :comments, through: :entries

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry

  validates :body, presence: true
  validates :entry_id, presence: true

  def approve
    update(status: 1)
  end

  def approved?
    status == 1
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :comments
  belongs_to :blog

  validates :blog_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
# coding: utf-8
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:success] = 'ブログを作成しました'
      redirect_to @blog
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      flash[:success] = 'ブログは更新されました'
      redirect_to @blog
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    flash[:success] = 'ブログは削除されました'
    redirect_to blogs_url
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title)
  end
end

app/controllers/comments_controller.rb
# coding: utf-8
class CommentsController < ApplicationController
  before_action :find_entry
  before_action :set_comment, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.entry_id = @entry.id
    if @comment.save
      flash[:success] = 'コメントが作成されました'
    else
      flash[:danger] = 'コメントを作成できませんでした'
    end
    redirect_to_entry
  end

  def update
    if @comment.update(comment_params)
      flash[:success] = 'コメントは更新されました'
    else
      flash[:danger] = 'コメントは更新できませんでした'
    end
    redirect_to_entry
  end

  def destroy
    @comment.destroy
    flash[:success] = 'コメントは削除されました'
    redirect_to_entry
  end

  def approve
    if @comment.approve
      flash[:success] = 'コメントは承認されました'
    end
    redirect_to_entry
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_entry
    @entry = Entry.find(params[:entry_id])
  rescue ActiveRecord::RecordNotFound
    head :not_found
  end

  def redirect_to_entry
    redirect_to blog_entry_path(blog_id: @entry.blog_id, id: @entry.id)
  end
end

app/controllers/entries_controller.rb
# coding: utf-8
class EntriesController < ApplicationController
  before_action :find_blog
  before_action :set_entry, only: [:show, :edit, :destroy, :update]

  def new
    @entry = Entry.new(blog_id: @blog.id)
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.blog_id = @blog.id
    if @entry.save
      flash[:success] = 'エントリーが作成されました'
      redirect_to @blog
    else
      render 'new'
    end
  end
  
  def edit
  end

  def show
  end

  def update
    if @entry.update(entry_params)
      flash[:success] = 'エントリーは更新されました'
      redirect_to @blog
    else
      render 'edit'
    end
  end
  
  def destroy
    @entry.destroy
    flash[:success] = 'エントリーは削除されました'
    redirect_to @blog
  end
  
  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:title, :body)
  end

  def find_blog
    @blog = Blog.find(params[:blog_id])
  rescue ActiveRecord::RecordNotFound
    head :not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blogs/_form.html.haml
= form_for(blog) do |f|
  = render 'shared/error_messages', model: blog

  %div(class='col-sm-6')
    %div(class='form-group')
      = f.label :title
      = f.text_field :title, class: 'form-control'
  
    %div(class='form-group')
      = f.button 'Submit', class: 'btn btn-primary'

app/views/blogs/edit.html.haml
%h1 Edit Blog

= render 'form', blog: @blog

app/views/blogs/index.html.haml
%h1 Blogs

%table(class='table')
  %thead
    %tr
      %th(colspan='2')
        Title

  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td
          = link_to 'Show', blog_path(blog), class: 'btn btn-info'
          = link_to 'Edit', edit_blog_path(blog), class: 'btn btn-primary'
          = link_to 'Destroy', blog_path(blog), method: :delete, data: {confirm: 'Do you want to destroy?'}, class: 'btn btn-danger'



= link_to 'New Blog', new_blog_path, class: 'btn btn-primary'

app/views/blogs/new.html.haml
%h1 New Blog

= render 'form', blog: @blog

app/views/blogs/show.html.haml
%h1= @blog.title

= fa_icon 'pencil-square-o'
= link_to 'Edit', edit_blog_path(@blog)
\|
= fa_icon 'backward'
= link_to 'Back', blogs_path


%h2 Entries

%table(class="table")
  %thead
    %tr
      %th Title
      %th Body
      %th Control

  %tbody
    - @blog.entries.all.each do |entry|
      %tr
        %td= entry.title
        %td= entry.body
        %td
          = link_to 'Show', blog_entry_path(@blog, entry), class: 'btn btn-info'
          = link_to 'Edit', edit_blog_entry_path(@blog, entry), class: 'btn btn-primary'
          = link_to 'Destroy', blog_entry_path(@blog, entry), method: :delete, data: {confirm: '削除してよろしいですか?'}, class: 'btn btn-danger'

= link_to 'New Entry', new_blog_entry_path(@blog), { class: 'btn btn-primary' }

app/views/entries/_form.html.haml
= form_for([entry.blog, entry]) do |f|
  = render 'shared/error_messages', model: entry
  
  %div(class='col-sm-4')
    %div(class='form-group')
      = f.label :title
      = f.text_field :title, class: 'form-control'

    %div(class='form-group')
      = f.label :body
      = f.text_area :body, class: 'form-control'
      
    %div(class='form-group')
      = f.button 'Submit', class: 'btn btn-primary'

app/views/entries/edit.html.haml
%div(class='page-header')
  %h1= @entry.blog.title

%h2 Edit Entry

= render 'form', entry: @entry

app/views/entries/new.html.haml
%div(class='page-header')
  %h1= @entry.blog.title

%h2 New Entry

= render 'form', entry: @entry

app/views/entries/show.html.haml
%h1= @entry.blog.title

%div(class='page-header')
  %h2= @entry.title

%div(class='panel panel-default')
  %div(class='panel-body')
    = @entry.body

%h2 Comments

%table(class='table')
  %tbody
    - @entry.comments.all.each do |comment|
      %tr
        - if comment.approved?
          %td= comment.body
          %td
        - else
          %td  (承認待ち)
          %td
            = link_to 'Approve', entry_comment_approve_path(@entry, comment), method: :patch,
            class: 'btn btn-primary'
        %td
          = link_to 'Destroy', entry_comment_path(@entry, comment), method: :delete,
          class: 'btn btn-danger', data: {confirm: '削除してよろしいですか?'}


%h3 New Comment

= form_for([@entry, @entry.comments.new], html: {class: 'form'}) do |f|
  %div(class='row')
    %div(class='col-sm-4')
      %div(class='form-group')
        = f.text_area :body, class: 'form-control'

      %div(class='form-group')
        = f.button 'Submit', class: 'btn btn-primary'

app/views/layouts/_footer.html.haml
%footer
  
  %p(class='text-center')
    = link_to 'Top', root_url
    %br/
    hello_rails

app/views/layouts/application.html.haml
!!!

%head
  %title Rails Sample Blog
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body

  %div(class='container')
    %div(class='row')
      - flash.each do |message_key, message|
        %div(class="alert alert-dismissible fade in alert-#{message_key}" role='alert')
          %button(type='button' class='close' data-dismiss='alert' aria-label='Close')
            %span(aria-hidden='true') &times;
          = message

      = yield

    = render 'layouts/footer'

app/views/shared/_error_messages.html.haml
- if model.errors.any?
  %div(id='error_explanation')
    %div(class='alert alert-danger')
      The form contains
      = pluralize(model.errors.count, 'error')

    %ul
      - model.errors.full_messages.each do |msg|
        %li= msg